name = "lustre_platform_opentui"
description = "Build OpenTUI apps using Lustre"
version = "0.0.1"
target = "javascript"
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre_platform = { git = "https://github.com/weedonandscott/lustre_platform", ref = "main" }
gleam_json = ">= 3.1.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
