name = "http_requests"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
lustre_platform = ">= 0.0.1 and < 1.0.0"
lustre_platform_opentui = { path = "../../../" }
rsvp = ">= 1.0.0 and < 2.0.0"
