name = "forms"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre_platform = ">= 0.0.1 and < 1.0.0"
lustre_platform_opentui = { path = "../../../" }
